apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: generals-tls-certificate
  namespace: istio-system
spec:
  secretName: generals-tls-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: generals.umu-art.ru
  dnsNames:
    - generals.umu-art.ru