apiVersion: apps/v1
kind: Deployment
metadata:
  name: g-ui
  namespace: generals
  labels:
    app: g-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: g-ui
  template:
    metadata:
      name: g-ui
      labels:
        app: g-ui
    spec:
      containers:
        - name: g-ui
          image: ghcr.io/umu-art/g-ui:latest
          imagePullPolicy: Always

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always

