name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs: { }


jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout g-core
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: maven

      - name: Build g-api
        working-directory: ./g-api
        run: chmod 777 ./build-server-api.sh && /bin/bash ./build-server-api.sh

      - name: Build and test g-core
        working-directory: ./g-core
        run: mvn -B package --file pom.xml

      - name: Build docker image
        uses: ./.github/workflows/actions/build_image
        with:
          image: g-core
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
