name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs: { }

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout g-ui
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: maven

      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Build g-api
        working-directory: ./g-api
        run: chmod 777 ./build-client-api.sh && ./build-client-api.sh ../g-ui/client

      - name: Install g-ui deps
        working-directory: ./g-ui
        run: npm install

      - name: Build g-ui
        working-directory: ./g-ui
        run: npm run build

      - name: Build docker image
        uses: ./.github/workflows/actions/build_image
        with:
          image: g-ui
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}


